local courseGeneratorPath = 'courseplay/course-generator/'
dofile( courseGeneratorPath .. 'Island.lua' )
dofile( courseGeneratorPath .. 'Genetic.lua' )
dofile( courseGeneratorPath .. 'courseGenerator.lua' )
dofile( courseGeneratorPath .. 'track.lua' )
dofile( courseGeneratorPath .. 'headland.lua' )
dofile( courseGeneratorPath .. 'center.lua' )
dofile( courseGeneratorPath .. 'geo.lua' )
dofile( courseGeneratorPath .. 'a-star.lua' )
dofile( courseGeneratorPath .. 'pathfinder.lua' )
dofile('courseplay/CpObject.lua')
dofile('courseplay/Waypoint.lua')

dofile( 'Vehicle.lua' )
dofile( 'file.lua' )
